### PR TITLE
Fix search for 0.4.16

### LINKED ISSUE #357: [Search][v0.4.16] Search Results template is broken
**Steps to Reproduce**
1. Click on Search bar
2. Enter value for search
3. Click on <enter> key
4. Pay attention to Search Results format

**Actual Results**
Seems template is broken

**Expected Results**
Search results should be visible in correct format in screen

Version: 0.4.16

https://user-images.githubusercontent.com/63799148/182213031-a9d60f7d-9efc-491a-9e59-9091c9bf1336.mov

### PR DESCRIPTION
**Pull request by melissawm**
Updates `0.4.16/_static/searchtools.js` to prevent a broken display of search results.

Note that if you test this locally, the text snippet below the search results is not shown, so this will need to be re-verified after merging.

Fixes #357

### CODE REVIEW

**Review by psobolewskiPhD — APPROVED** [review]

**Comment by psobolewskiPhD** [comment]
Thanks for getting this sorted!!
❤️

**Comment by melissawm** [comment]
Hi folks - gentle ping, is there anything else I can do here?

**Comment by jni** [comment]
I don't understand this but YOLO! 😅

**Comment by psobolewskiPhD** [comment]
> I don't understand this but YOLO! 😅
> 
> 

It worked 😉

**Pull request merged**
