### PR TITLE
Add information about add method and add_<shape_type> methods

### PR DESCRIPTION
**Pull request by DragaDoncila**
Update `Shapes` tutorial to include information about

- `add` method for adding mixed shape types to an existing layer
- `add_<shape_type>` methods for adding each individual shape type

### CODE REVIEW

**Comment by DragaDoncila** [comment]
Tests are failing because the individual `add` methods aren't recognised yet - not sure what the typical workflow is for updating tutorials but I guess might have to wait for release on this

**Comment by tlambert03** [comment]
ah, good point.  I think this is just the first time we've run into this... but it might be reasonable to use the master branch for our [requirements.txt](https://github.com/napari/napari.github.io/blob/master/requirements.txt) here?

maybe try:

```
napari @ git+https://github.com/napari/napari.git
pyqt5
```

or something like that?

**Comment by DragaDoncila** [comment]
> ah, good point. I think this is just the first time we've run into this... but it might be reasonable to use the master branch for our [requirements.txt](https://github.com/napari/napari.github.io/blob/master/requirements.txt) here?
> 
> maybe try:
> 
> ```
> napari @ git+https://github.com/napari/napari.git
> pyqt5
> ```

sorry just to clarify, is this going in `requirements.txt`

**Comment by tlambert03** [comment]
yep,  the tests here [install requirements.txt](https://github.com/napari/napari.github.io/blob/62f38db138c3a116b9b978b9bbb5420a082d1c57/.github/workflows/test.yml#L38)... so if we want to use the master branch, we need to edit requirements.txt to pull from github.  I think that syntax will work, but you may need to try other things

**Comment by DragaDoncila** [comment]
@tlambert03 awesome, thanks for the tip, I'll try a few things.

**Comment by DragaDoncila** [comment]
Ok so that's worked. I'm not sure whether we want to always be pulling from master though. Is there a danger that docs and latest release become out of sync if we do that?

**Comment by tlambert03** [comment]
@kne42 would have to answer that.  I'm still not quite sure how much of the docs are manually done vs automatic and how versioning is working

**Comment by kne42** [comment]
There is currently no versioning of the docs set up yet so it defaults to `dev`. There are plans to add versioning to certain aspects of the docs (see below)

website source organization

As you can see, tutorials are not one of the sections planned to be versioned as of yet since we'd hope users are keeping their installation up-to-date. If you think they should we could also discuss that. To prevent the tutorials being out of sync with the latest release, I would suggest waiting to merge until the version it's based upon has been released for now.

**Comment by DragaDoncila** [comment]
@kne42 thanks for the update. In that case, I will revert the change to `requirements.txt` pulling from `master` and we will wait for napari release before merging this.

**Comment by DragaDoncila** [comment]
@tlambert03 are you able to rerun checks on this PR - now that we've released we should try merge this soon.

**Review by tlambert03 — APPROVED** [review]

**Pull request merged**
