### PR TITLE
Switch link formatting, ready for jupyter book

### PR DESCRIPTION
**Pull request by GenevieveBuckley**
When this PR is merged, we need to switch the website to show jupyterbook.

cc @kne42 

This pull request:
* switches the formatting of relative image links, so they work with jupyterbook
* removes page footers (this is now unnecessary since we're using jupyterbook)
* removes the gif table from the gallery page (only because it wasn't rendering correctly, we're happy for a later PR to add this back in if people want)
* fixes a broken link to the contributing.md guide on github
* Adds more meaningful alt text to all the images displayed.

### CODE REVIEW

**Comment by jni** [comment]
Wow, nice work! Changes look good to me but do you know why the build fails?

**Comment by GenevieveBuckley** [comment]
No, I don't know why the build is failing. But this one's important so we need to fix it.

It passes locally on my machine, in my napari-dev environment (which has python 3.7)

**Comment by GenevieveBuckley** [comment]
I wonder if it has something to do with the face the CI machines have no screens (and therefore we're having trouble creating screenshots again).

Previously, we thought we'd solved this issue by using this virtual screen:
https://github.com/napari/tutorials/blob/6e77fea3548baed7989645f765ebbc602c046c80/.github/workflows/deploy.yml#L33-L37

**Comment by GenevieveBuckley** [comment]
Here's some of the discussion we had around these problems earlier. Maybe @ziyangczi has a suggestion here too.

https://github.com/napari/tutorials/pull/95#issuecomment-722559541

**Comment by liu-ziyang** [comment]
> Here's some of the discussion we had around these problems earlier. Maybe @ziyangczi has a suggestion here too.
> 
> [#95 (comment)](https://github.com/napari/tutorials/pull/95#issuecomment-722559541)

from the very little error message I read(kernel didn't give stacktrace), the cell 2 (nbscreenshot) somehow timed out and resulted in a failure, I don't immediately see its connection with display mechanisms not setting up properly (I would expect an immediate failure complaining about not able to find a display to initialize the viewer in that case). Unfortunately, I don't know the screenshot function well enough to tell why it would hang... I would recommend comment out the nbscreenshot and maybe give it a try and see if everything else is working as expected

**Comment by tlambert03** [comment]
you might also have a look at the jupyter-book build I'm using at magicgui: https://github.com/napari/magicgui/blob/master/.github/workflows/deploy_docs.yml

looks like I'm using a few extra libraries there that might help?

**Comment by GenevieveBuckley** [comment]
So it seems the jupyter-book builds have been failing for the last three months. Several things have changed in the surrounding ecosystem since then. Most relevantly, the github actions `ubuntu-latest` has changed from Ubuntu 18.04 to Ubuntu 20.04, and there have also been [several new releases of jupyter-book](https://github.com/executablebooks/jupyter-book/releases)

I'm going to try pinning to `ubuntu-18.04` in our github actions script `deploy.yml` and see if that helps.
EDIT: nope, it's not that.

**Comment by GenevieveBuckley** [comment]
> you might also have a look at the jupyter-book build I'm using at magicgui: https://github.com/napari/magicgui/blob/master/.github/workflows/deploy_docs.yml
> 
> looks like I'm using a few extra libraries there that might help?

This worked! You have quite a few extra libraries there...

Now we're just stuck because of a permissions error pushing to the github pages branch. I'll check if we need to regenerate an auth token or something.

**Comment by GenevieveBuckley** [comment]
It is not clear to me why it says we don't have permission to write to the gh-pages branch with  `GITHUB_TOKEN`. It's supposed to just work out of the box, and was working well last time I tried this.

I've been fiddling with other authentication keys & secrets, no luck so far. @tlambert03 nothing here looks that different to the magicgui docs build workflow, do you have any ideas for me to try?

Failure is at the step "GitHub Pages action"
```
Push the commit or tag
  /usr/bin/git push origin gh-pages
  remote: Permission to napari/tutorials.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/napari/tutorials.git/': The requested URL returned error: 403
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 128"
```

As far as I can tell, our setup was working before and should also be working now. From https://github.com/peaceiris/actions-gh-pages
> A GitHub Actions runner automatically creates a GITHUB_TOKEN secret to authenticate in your workflow. So, you can start to deploy immediately without any configuration.

**Review by kne42 — APPROVED** [review]
Great work @GenevieveBuckley! I think the issue you're running into with the CI building the docs is that since this is a PR, I'm fairly sure that it restricts access to the `GITHUB_TOKEN` secret. I would merge for now and if it's still broken after we can work on debugging it :)

**Comment by tlambert03** [comment]
> @tlambert03 nothing here looks that different to the magicgui docs build workflow, do you have any ideas for me to try?

it might also be `gh-pages` settings in https://github.com/napari/tutorials/settings:

Untitled

you might need to change that to `/root`?

**Comment by tlambert03** [comment]
(magicgui settings:)

Untitled 2

**Comment by GenevieveBuckley** [comment]
> Great work @GenevieveBuckley! I think the issue you're running into with the CI building the docs is that since this is a PR, I'm fairly sure that it restricts access to the `GITHUB_TOKEN` secret. I would merge for now and if it's still broken after we can work on debugging it :)

Oh ok. I'm sure this *used* to work though! If you're right about this, maybe we'll need an if statement in the `deploy.yml`, so it only tries to do the push if it's from the main `napari/tutorlias` repository

**Comment by GenevieveBuckley** [comment]
@tlambert03 I did change which branch & directory was being used for github pages, but changed it back when I needed to go to bed. (It's entirely possible I didn't change it back properly, but I was trying to leave it like I found it)

**Comment by GenevieveBuckley** [comment]
Ok, let's merge this and test Kira's theory...

**Comment by GenevieveBuckley** [comment]
:tada: You are right @kne42 :tada: 

Thanks so much, I got really bogged down here & would not have realized on my own!

**Pull request merged**
