### PR TITLE
Landing page quick links

### PR DESCRIPTION
**Pull request by codemonkey800**
## Description

This renders the grid of links + descriptions at the bottom of the landing page. This works by adding a new frontmatter key called `quickLinks` that accepts a list of objects with the format:

```yml
theme:
  quickLinks:
    - title: Community
      content: Meet the team, our mission, and our values
      url: /community/index.html
    ...
```

## Demo

https://napari-org-grid-toc.vercel.app/#help

image

### CODE REVIEW

**Review by liaprins-czi — CHANGES_REQUESTED** [review]
Excited to see this! There are just a couple of things to update and to note:
- The headers should be Sentence case (to match the ideal way of doing titles of documentation also), so basically only the first letter of the entire heading should be capitalized, not the First Letter of Each Word (right now it is a mix of both approaches)
- The text descriptions for each are just what I had written as placeholder and based on my own knowledge, but it'd be good to have @sofroniewn et al finalize and probably have @melissawm input too! But in the meantime, the descriptions for Developer resources and Source code look like they are copy--and-paste of Developer guides: all three have the same but the last couple don't match what i had as placeholder / my-best-guess text.
- It looks like the left side fo the left-most items are slightly indented compared to the rest of the text
- At narrower screen sizes, the width of the grid items should expand (there just needs to maintain the horizontal (and vertical) spacing), but they should widen accordingly when there are less grid items to fit across
Screen Shot 2021-09-21 at 2 13 53 PM

Other than that I think it looks good to me 👍

**Comment by codemonkey800** [comment]
Thanks for the feedback @liaprins-czi! I'll work on this right away. 

> The text descriptions for each are just what I had written as placeholder and based on my own knowledge, but it'd be good to have @sofroniewn et al finalize and probably have @melissawm input too! But in the meantime, the descriptions for Developer resources and Source code look like they are copy--and-paste of Developer guides: all three have the same but the last couple don't match what i had as placeholder / my-best-guess text.

The glory of programming is copy-and-paste 😆  I'll fix those items so that they use the correct descriptions. As for the content in general, I think that's fine since there are some content changes we'll need to update so that it works nicely with the theme. This can come before or during the [content refactor](https://github.com/napari/napari/issues/3390#issuecomment-924221681).

**Review by justinelarsen — APPROVED** [review]
LGTM! 💨 🔗

**Comment by codemonkey800** [comment]
@liaprins-czi the styling has been updated. Could you take another look please 😄

**Comment by sofroniewn** [comment]
> The text descriptions for each are just what I had written as placeholder and based on my own knowledge, but it'd be good to have @sofroniewn et al finalize and probably have @melissawm input too!

@jni can you take a look at this too. Will this PR make the changes go live, or can they get merged and then can we refine to copy later. I don't want to be the bottleneck on getting this merged, but also the copy should get reviewed/ lined up with proposals from @melissawm (right now it looks like the text for Dev Guides and Dev Resources is the same for example).

**Comment by codemonkey800** [comment]
> > The text descriptions for each are just what I had written as placeholder and based on my own knowledge, but it'd be good to have @sofroniewn et al finalize and probably have @melissawm input too!
> 
> @jni can you take a look at this too. Will this PR make the changes go live, or can they get merged and then can we refine to copy later. I don't want to be the bottleneck on getting this merged, but also the copy should get reviewed/ lined up with proposals from @melissawm (right now it looks like the text for Dev Guides and Dev Resources is the same for example).

I didn't include any copy changes in this PR so nothing will change on the current documentation. Also the theme is still disabled so merging this won't change the docs, giving us time to refine the copy before we fully release the theme.

**Comment by sofroniewn** [comment]
> I didn't include any copy changes in this PR so nothing will change on the current documentation. Also the theme is still disabled so merging this won't change the docs, giving us time to refine the copy before we fully release the theme.

Ok nice, yeah i just realized I was reading the wrong text in an old screenshot, not the stuff in the link which look good

This all looks good to me then, merge when ready 🚀

**Review by sofroniewn — APPROVED** [review]

**Pull request merged**
