### PR TITLE
Enables the napari theme for production

### PR DESCRIPTION
**Pull request by codemonkey800**
🎉  Enables the napari theme for production 🎉 

We recently finished our rounds of QA testing and bug fixes, and we feel ready to release the new napari.org theme to production.

The staging site can be viewed here for an idea of what's to come: https://napari.staging.imaging.cziscience.com

### CODE REVIEW

**Comment by tlambert03** [comment]
so cool.  great work all!

I don't see an open issue for it, so just want to mention the one thing that I think would be great to address before release, which is the size of the page TOC on "medium size screens...  For example: here's how it looks on a pretty typical browser width on my 4K monitor with 2x scaling:

Untitled

It be nice if we could get more of that page "above the fold" and not dedicate the majority of the visual space to the page TOC.

**Comment by codemonkey800** [comment]
> so cool. great work all!
> 
> I don't see an open issue for it, so just want to mention the one thing that I think would be great to address before release, which is the size of the page TOC on "medium size screens... For example: here's how it looks on a pretty typical browser width on my 4K monitor with 2x scaling:
> 
> Untitled
> 
> It be nice if we could get more of that page "above the fold" and not dedicate the majority of the visual space to the page TOC.

Ahhh I thought I addressed this one, but I guess not. I'm on it!

**Comment by sofroniewn** [comment]
Looking great! I had one minor question. On some of the "index" pages it looks like some bullets get duplicated, see below. Is that intentional? Do others see it too? I find it a little confusing, but maybe i'm missing something

image

**Comment by codemonkey800** [comment]
> Looking great! I had one minor question. On some of the "index" pages it looks like some bullets get duplicated, see below. Is that intentional? Do others see it too? I find it a little confusing, but maybe i'm missing something
> 
> image

Yeah some of the index pages have the TOC as part of the page, but the theme already adds one so it's added twice by accident. I'll update the content to remove it!

**Review by sofroniewn — APPROVED** [review]
Looks great! Love it, i'm ready for this to go live. Might be nice to get one or two more approvals before merge though. Great work @codemonkey800 @kne42 @liaprins-czi and team!!!

**Comment by codemonkey800** [comment]
> Looks great! Love it, i'm ready for this to go live. Might be nice to get one or two more approvals before merge though. Great work @codemonkey800 @kne42 @liaprins-czi and team!!!

Thank you! We'll also need to wait for #202 to be merged to resolve https://github.com/napari/napari.github.io/pull/201#issuecomment-941742959 before merging

**Review by jni — APPROVED** [review]

**Review by klai95 — APPROVED** [review]

**Review by neuromusic — APPROVED** [review]
Looks great!! Nice work! If no major issues come up, let's land this (and deploy to production) on Monday

**Pull request merged**
