### PR TITLE
Remove extra space in admonitions

### LINKED ISSUE #363: [How to install napari][v0.4.16] Blue boxes are not showing content and do not match with v0.4.15
Steps to Reproduce

1. Go to Getting started -> How to install napari on your machine
2. Navigate to Install as Python package (recommended) section
3. Pay attention to blue boxes

Actual Results
They seem empty until you click on them

Expected Results
They shouldn't look empty or should be collapsed

image

### PR DESCRIPTION
**Pull request by melissawm**
Fixes napari/napari-sphinx-theme#99
Fixes #363

### CODE REVIEW

**Comment by melissawm** [comment]
Ok folks - due to all the changes related to themes and versions since version 0.4.16, the easiest solution seems to be to manually fix these dropdowns for that version, since they are fixed (I think?) in latest.

@codemonkey800 would you mind checking this out? Thanks!

**Comment by jni** [comment]
@melissawm I don't really know how to review this... Would you mind walking me through it? (Possibly through comments on the diff — I'm actually travelling this week and next so sync will be challenging for a bit.)

**Review by codemonkey800 — APPROVED** [review]
LGTM, thank you!!

**Comment by melissawm** [comment]
Hey folks - gentle ping :) Should I self-merge or can someone else do it for me? Thanks!

**Comment by melissawm** [comment]
Another gentle ping just in case 😄

**Pull request merged**
