### PR TITLE
update point size variable names

### PR DESCRIPTION
**Pull request by alisterburt**
point size attribute names in the tutorial for the points layer were outdated - updated accordingly!

### CODE REVIEW

**Review by goanpeca — APPROVED** [review]
Thanks @alisterburt !

**Comment by alisterburt** [comment]
thanks @goanpeca - I'm not sure what's going on with the tests, have you seen these errors before on this repo?

**Comment by goanpeca** [comment]
> I'm not sure what's going on with the tests, have you seen these errors before on this repo?

Hi @alisterburt can you add this step in your PR, to get that fix in ?

https://github.com/napari/napari.github.io/pull/134/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R46

**Comment by alisterburt** [comment]
thanks for the suggestion - added and still failing but I see in #134 that the 'stable' tests fail there whilst the 'master' tests succeed so I think we're probably okay

**Comment by tlambert03** [comment]
These errors happen if there are unclosed windows when the test quits.  So if you can think of where a stray window might still be open and close it, it might fix it.

**Comment by melissawm** [comment]
If this is still applicable, can we move these changes to napari/napari?

**Comment by alisterburt** [comment]
I would have to check but I think so! AFK right now but will add to the list :)

**Comment by psobolewskiPhD** [comment]
This change is already live in https://github.com/napari/docs
image

**Pull request closed without merging**
