### PR TITLE
Update TOC design for smaller screens

### PR DESCRIPTION
**Pull request by codemonkey800**
## Description

Updates the TOC to use a collapsible layout for smaller screens so that it takes up less vertical space.

## Demo

https://napari-org-collapsible-toc.vercel.app

https://user-images.githubusercontent.com/2176050/137065489-37d49cc0-9e70-4e5b-b94b-730e9dcda071.mp4

### CODE REVIEW

**Comment by codemonkey800** [comment]
@tlambert03 If you get a chance, could please test out the new design and let me know if this resolves https://github.com/napari/napari.github.io/pull/201#issuecomment-941742959? 😄 

Demo link: https://napari-org-collapsible-toc.vercel.app/

**Review by kne42 — APPROVED** [review]
ooh nice i like it. only thing is what's with the icon name o.0

**Comment by neuromusic** [comment]
> what's with the icon name

https://en.wikipedia.org/wiki/Chevron_(insignia)

it's what the gas company is named after 😄

**Comment by kne42** [comment]
oh wow TIL

**Comment by neuromusic** [comment]
@codemonkey800 its only collapsing for me on the most narrow width (when the left/global ToC disappears)... at the width @tlambert03 noted, it is still expanded:

image

also there's a stray semicolon:

image

**Comment by tlambert03** [comment]
nope, 1150px to 1424px still looks pretty strange.  basically, I don't think there should ever be an expanded page TOC above the content:

https://user-images.githubusercontent.com/1609449/137187669-90a81e85-305c-400d-9d14-295bebe7d228.mov

**Comment by codemonkey800** [comment]
> nope, 1150px to 1424px still looks pretty strange. basically, I don't think there should ever be an expanded page TOC above the content:
> 
>  Untitled.mov

Got it, so the TOC should always be collapsed by default ~regardless of the screen width~ when the TOC is above the content?

**Comment by codemonkey800** [comment]
> @codemonkey800 its only collapsing for me on the most narrow width (when the left/global ToC disappears)... at the width @tlambert03 noted, it is still expanded:
> 
> image
> 
> also there's a stray semicolon:
> 
> image

that's a fun bug, i forgot to remove a semicolon somewhere in the render code 😆

**Comment by tlambert03** [comment]
> TOC should always be collapsed by default regardless of the screen width?

in the 2-column config, when the TOC is above the content, it should be collapsed.  The three column layout is fine:
Untitled copy

**Comment by codemonkey800** [comment]
@neuromusic the random semicolon has been removed, and @tlambert03 I've updated the TOC to be collapsed for the 1-column and 2-column layouts 😄 

https://napari-org-collapsible-toc.vercel.app/

**Comment by tlambert03** [comment]
gorgeous! :)

for bonus points, what do you think of adding a scroll when a toc link is pressed?

**Review by tlambert03 — APPROVED** [review]

**Comment by codemonkey800** [comment]
> gorgeous! :)
> 
> for bonus points, what do you think of adding a scroll when a toc link is pressed?

Actually it should scroll when clicking on the link. Does it not do that right now? 😢

**Comment by tlambert03** [comment]
> Actually it should scroll when clicking on the link. Does it not do that right now? 😢

hmmm.  not for me, tried in chrome and safari (with various widths).  anything I can do to help debug?  does it work for you?

**Comment by codemonkey800** [comment]
> > Actually it should scroll when clicking on the link. Does it not do that right now? 😢
> 
> hmmm. not for me, tried in chrome and safari (with various widths). anything I can do to help debug? does it work for you?

Would be nice to know your OS and browser versions, and a video of the problem you're encountering. And yes, it's working for both Chrome and Safari on my end:

https://user-images.githubusercontent.com/2176050/137202896-09a4ad6e-8b56-4495-9017-56bd92f8f021.mp4

**Comment by tlambert03** [comment]
ah... ok, semantics.  mine has the same behavior.  I wouldn't call that a "_scroll_" ... I'd say it jumps straight to the link :) 
I'm referring to this sort of behavior https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

This is really a minor aesthetic issue (that's why I said bonus points).  go ahead and merge this PR and save that for a future consideration.

**Comment by codemonkey800** [comment]
> ah... ok, semantics. mine has the same behavior. I wouldn't call that a "_scroll_" ... I'd say it jumps straight to the link :) I'm referring to this sort of behavior https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView
> 
> This is really a minor aesthetic issue (that's why I said bonus points). go ahead and merge this PR and save that for a future consideration.

Ahh I see, I get what you mean now. Yeah it's something we could add but there's also some fancy logic in there that also handles scrolling on page load, so I'd rather we tackle it in a separate PR. I've created https://github.com/napari/napari.github.io/issues/204 to track it 😄

**Review by klai95 — APPROVED** [review]
LGTM!

**Pull request merged**
