### PR TITLE
Add unversioned pages workflow to gh-pages branch

### PR DESCRIPTION
**Pull request by melissawm**
@psobolewskiPhD and I have been trying to check the documentation for the workflow events and it is not clear if we should have the workflow on the main branch. This is a proposal to try having it in the gh-pages branch based on https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#about-workflow-triggers

### CODE REVIEW

**Review by psobolewskiPhD — APPROVED** [review]

**Review by jni — APPROVED** [review]

**Comment by melissawm** [comment]
Well, it looks like this has finally worked and @psobolewskiPhD was right!!! https://github.com/napari/napari.github.io/actions/runs/9867863556

I'll send a PR to remove the action from the main branch and I think we are finally done 🎉

**Comment by melissawm** [comment]
Actually I'm not sure - it looks like this got triggered by a push to gh-pages when we merged this PR, but the workflow file mentioned in the actions is the one from main? I will keep watching for the next merge on napari or napari/docs and see what happens.

**Comment by jni** [comment]
So friggin confusing...

Genuinely though I'm not suuuuuper worried about having this be manual in the short term.

**Comment by psobolewskiPhD** [comment]
Not sure about the canceled jobs, but I think it's working?
image

**Comment by psobolewskiPhD** [comment]
Maybe it's concurrency settings in the workflows?
image

**Comment by melissawm** [comment]
Here's my understanding, which is not necessarily complete:
- The page-build event triggers the unversioned workflow _at the same time_ as the page build, which is then cancelled as waiting for the other workflow. Once the unversioned workflow is complete, the page build is triggered again. I'm not sure how to avoid that but will check.
- The workflow is definitely working and seemingly from the gh-pages branch?

**Pull request merged**
