### PR TITLE
Theme download button

### LINKED ISSUE #279: Add JupyterBook download buttons to napari tutorials
I seem to remember that in the old napari.org theme, MyST markdown tutorials like the [installation tutorial](https://napari.org/tutorials/fundamentals/installation.html) had download buttons at the top, similar to the [numpy docs](https://numpy.org/numpy-tutorials/content/tutorial-deep-learning-on-mnist.html).

image

As part of the work on documentation we will update all our tutorials and how-to guides to MyST markdown, so that they can be easily downloaded by users who want to run them as notebooks. It would be great if we could bring back these buttons for the new theme. 

Pinging @liaprins-czi as this may require some design work, and @neuromusic to flag that we might want this relatively soon after the docs reorg is complete, depending on what engineering effort is required - @codemonkey800 maybe you have an idea already.

### PR DESCRIPTION
**Pull request by codemonkey800**
## Description

Implements the download button described in #279. 

## Demo

https://napari-org-download-button.vercel.app

image

### CODE REVIEW

**Comment by codemonkey800** [comment]
@liaprins-czi couple of questions:

1. Should the link to the Markdown source open in the browser or force a download? Right now it opens it in the browser:
    
    image
1. Should we limit the download button to only tutorial pages? Jupyter Book will output Markdown sources for every file, so the download button also shows up on non-tutorial pages.

**Review by liaprins-czi — COMMENTED** [review]
@codemonkey800 Thanks for implementing this, it looks good to me!

As for your questions, I am not sure... I think @DragaDoncila could have better sense of what weould be expected from a user POV, or a better experience for them. I do not think we should have the download button on the main home page after the title "napari" , because ppl might think it means that is how they download the actual napari app.

**Comment by DragaDoncila** [comment]
@codemonkey800 thanks for this, it's looking great! As for your questions:

> Should the link to the Markdown source open in the browser or force a download?

It should force a download. If it opens source in browser the default extension ends up being `.txt` and the user has to manually change it. Ideally, clicking the button would open a save dialog with a `.md` extension.

> Should we limit the download button to only tutorial pages?

Yes, I think so. It's confusing to have it on every page. I'm not sure how this would be implemented, but I'm curious - is there a world where we could easily specify on a given document whether it does or does not get a download button e.g. via some jupytext metadata?

**Comment by codemonkey800** [comment]
@DragaDoncila sounds good! I've pushed some fixes to force the Markdown download and to limit the download button to only tutorial pages. But if we want to, we can still add some code to render the download button if there's metadata for it. Do you have any use cases for when we want to add the button outside of tutorials?

**Review by DragaDoncila — APPROVED** [review]
@codemonkey800 this looks good to me and I think it can go in.

A small thing I noticed is saving to PDF triggers the print menu (I assume so you can print to pdf). If we could change that to just download a pdf that would be great, but totally not critical.

In terms of "things other than tutorials" that we may want to download, the one concrete example I can think of is the docs template we'll soon be adding (see #283). But I also think long term we may not be able to just point to one folder/section as "everything in here is downloadable". I'm not sure how challenging this would be to implement so I'm ok to leave it for a follow up PR.

**Comment by codemonkey800** [comment]
> A small thing I noticed is saving to PDF triggers the print menu (I assume so you can print to pdf). If we could change that to just download a pdf that would be great, but totally not critical.

I originally thought it was impossible, but it looks like there's a trick to get it working iframes. There's a library that does it, so I'll look into using it: https://printjs.crabbly.com/#documentation

> But I also think long term we may not be able to just point to one folder/section as "everything in here is downloadable". I'm not sure how challenging this would be to implement so I'm ok to leave it for a follow up PR.

Let's implement in a future PR! It shouldn't be too difficult to implement: we can either add another theme variable in the frontmatter metadata as you mentioned, or we can maintain a set of URLs somewhere to check what pages to render with a download button.

**Comment by codemonkey800** [comment]
@DragaDoncila so I did a bit of experimenting and the results of the generated PDF are not as good. I ended up trying out [html2pdf](https://ekoopmans.github.io/html2pdf.js), which works by rendering the HTML to Canvas and writing the data to a pdf using [jspdf](https://www.npmjs.com/package/jspdf).

It works well, but `html2pdf` is only an approximation of what the DOM looks like, so there may be inconsistencies. The first one I noticed was on the tutorials index page:
image

And here's the same paragraph generated by the print dialog:
image

So the issue is that using the library above may result in content that is unreadable.

**Comment by codemonkey800** [comment]
The default behavior for Jupyter Book is to show the print dialog when clicking on the PDF download option, so I think it's fine if we stick with it for now (at least until PDF printing APIs get better for browsers 😆)

Kapture 2021-12-02 at 13 41 05

**Comment by DragaDoncila** [comment]
@codemonkey800 yep I think that's fine - to be honest I don't think the `.pdf` button will be used frequently, if at all, so I don't think we should engineer much to support it

As for adding support for different documents/folders, I will ping you once we've moved along with the docs reorg and have some concrete folders/docs that we want to include.

**Pull request merged**
