### PR TITLE
Remove all things from main

### PR DESCRIPTION
**Pull request by jni**
As suggested by @neuromusic in [this comment](https://github.com/napari/napari/pull/4183#issuecomment-1056210939), this PR removes everything from the repo and clears the README to a barebones message pointing users to our contributing guide (soon to be a docs contributing guide).

### CODE REVIEW

**Comment by jni** [comment]
Here's the README btw, because navigating all the deleted files is horrible:

https://github.com/napari/napari.github.io/blob/021eed08ae477001846da8efe8298a8e907b59f2/README.md

**Review by tlambert03 — APPROVED** [review]
Good by me!  Might be nice for @codemonkey800 to sign off on this one too though

**Review by codemonkey800 — APPROVED** [review]
Some of the code in here is still valuable, so I moved it to a personal fork for future reference:
https://github.com/codemonkey800/napari.github.io

LGTM, let's clean things up 😃

**Comment by tlambert03** [comment]
thanks @codemonkey800!

**Pull request merged**
