### PR TITLE
adds napari survey CTA

### PR DESCRIPTION
**Pull request by neuromusic**
This PR adds a temporary callout inviting visitors to the napari.org site to participate in the annual user survey.

We can plan to take this down ~ Dec 21

### CODE REVIEW

**Review by sofroniewn — COMMENTED** [review]
I like this will help drive traffic to survey which will be great. I'm very supportive. Any concerns @jni?

**Review by GenevieveBuckley — APPROVED** [review]

**Comment by neuromusic** [comment]
@melissawm any concerns about this landing before #299?

**Comment by melissawm** [comment]
> @melissawm any concerns about this landing before #299?

No, looks good to me!

**Comment by GenevieveBuckley** [comment]
If you're planning to remove this notice around Dec 21, it's probably best to get this in sooner rather than later, so I'll merge it now.

I don't see anything controversial that Juan might be concerned about, and I know that he's pretty busy right now.

**Comment by neuromusic** [comment]
Thanks @GenevieveBuckley, agreed! :D

I was trying to do my due diligence and wait the full 24 hrs after an approval... I was just counting down the minutes :P

**Comment by GenevieveBuckley** [comment]
Ah, I didn't realize we had a strict rule about it

**Comment by neuromusic** [comment]
Not strict, I suppose...

> It should also be considered best practice to leave a reasonable (24hr) time window after approval before merge to ensure that other core developers have a reasonable chance to weigh in.

via https://napari.org/developers/core_dev_guide.html#all-contributors-are-treated-the-same

**Pull request merged**
