### PR TITLE
Add 'Preparing your notebook' tutorial

### PR DESCRIPTION
**Pull request by DragaDoncila**
Based on discussion in #181 this PR adds a tutorial for preparing Jupyter notebooks for contribution to our documentation.

It covers:
- using `nbscreenshot`
- hiding jupyter notebook cells
- pairing notebook with MyST markdown

It doesn't cover opening a PR, because I plan to put that in the individual "How to how to" guides so we can tell users what directory they should place their documentation in.

Notes/questions for review:
- I haven't covered directions for Jupyter lab, just Jupyter notebook and from the command line. I'm not sure how commonly this is used and if we should add it?
- This was my first time using Jupyter notebook in a long time, and my first time ever using Jupytext so someone more familiar with these should check my terminology and suggestions to see if they're suitable
- This is actually a tutorial, and we don't have a "how to write a tutorial" tutorial yet, which means we don't have a template either. I borrowed heavily for this tutorial from [this numpy guide](https://numpy.org/numpy-tutorials/content/tutorial-style-guide.html#further-reading) @melissawm pointed me towards. I really like this flow in general - so maybe when reviewing this tutorial, also review it as fitting into our future template (which I will be contributing next week)? 

Random note:
What's the guideline (do we have one?) for word wrapping in markdown files? I've been adding newlines wherever I feel it's getting too long but that might end up looking weird for other people's computers?

### CODE REVIEW

**Comment by GenevieveBuckley** [comment]
> I haven't covered directions for Jupyter lab, just Jupyter notebook and from the command line. I'm not sure how common;y this is used and if we should add it?

I think this is fine. The people who like jupyter lab will already know about it or already be using it, and it's probably more straightforward for newbies to get started with a plain jupyter notebook.

**Comment by GenevieveBuckley** [comment]
> What's the guideline (do we have one?) for word wrapping in markdown files? I've been adding newlines wherever I feel it's getting too long but that might end up looking weird for other people's computers?

I don't think there is a hard and fast guideline, but if you're worried about things looking "weird" to other people you could aim for line lengths that are roughly similar to the python 80 character recommended line length before wrapping.

I personally do find it helpful to put different sentences on different lines in the markdown file, even if they are getting rendered as part of the same paragraph. I like this because it's easier to look at the git diff and see what the change is if you're looking at one sentence instead of four sentences from the same paragraph. As for line breaks mid-sentence, I don't have a strong opinion about it, I think people generally do what feels right to them.

**Comment by GenevieveBuckley** [comment]
This is pretty good overall, but I think we're missing:
1. Instructions on how to access/download the template
2. How to get the template up and running with jupyter on their local machine (especially imprtant if people might have downloaded the text file representation of the template). I see you have some jupytext instructions, but only at the end. Perhaps we need some at the beginning too?
3. Connecting/linking this template document with the main how to guide (I think we're hoping most people start with a how to guide first, and then download the template while going through those steps, but there might still be some people stumble across this doc first, and we want them to know they're mid-way)

**Comment by GenevieveBuckley** [comment]
Is this is superseded by https://github.com/napari/napari.github.io/pull/283

**Comment by DragaDoncila** [comment]
@GenevieveBuckley yes, this is superseded by #283, which we will close once we are happy with the overall approach and reopen in `napari/napari`.

Closing this PR now.

**Pull request closed without merging**
