### PR TITLE
Complementing changes to add tutorials to main repo

### PR DESCRIPTION
**Pull request by melissawm**
Second part of napari/napari#3815

Final part of #176

### CODE REVIEW

**Comment by melissawm** [comment]
It looks like there was a change in napari that broke the Image tutorial:

```
E       TypeError: add_image() got an unexpected keyword argument 'contrast_limit'
```

**Comment by sofroniewn** [comment]
>E       TypeError: add_image() got an unexpected keyword argument 'contrast_limit'

I think it should be `contrast_limits` plural. can you try updating that

**Comment by melissawm** [comment]
That did the trick, thanks @sofroniewn - I wonder how this was passing before? Anyways, all good on my side :)

**Review by sofroniewn — APPROVED** [review]
LGTM! All tests passing

**Pull request merged**
