### PR TITLE
Meta previews

### LINKED ISSUE #277: add meta info to headers to enable link previews in image.sc, etc
When users link to napari documentation in sites such as image.sc, Twitter, Slack, etc, we can enable rich previews by adding the appropriate meta tags to the header.

- image.sc/Discourse: https://meta.discourse.org/t/rich-link-previews-with-onebox/98088
- Twitter: https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/abouts-cards

If we take https://napari.org/tutorials/applications/annotate_segmentation.html as an example, this would look something like the following, with the content generated dynamically for each page (including grabbing one of the images in the page for the preview):

``` HTML
<!-- Twitter Card data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@napari_imaging">
<meta name="twitter:title" content="annotating segmentation with text and bounding boxes">
<meta name="twitter:description" content="In this tutorial, we will use napari to view and annotate a segmentation with bounding boxes and text labels.">
<meta name="twitter:creator" content="@napari_imaging">
<!-- Twitter Summary card images must be at least 120x120px -->
<meta name="twitter:image" content="https://napari.org/_images/annotated_bbox.png">

<!-- Open Graph data -->
<meta property="og:title" content="annotating segmentation with text and bounding boxes." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://napari.org/tutorials/applications/annotate_segmentation.html" />
<meta property="og:image" content="https://napari.org/_images/annotated_bbox.png" />
<meta property="og:description" content="In this tutorial, we will use napari to view and annotate a segmentation with bounding boxes and text labels. " />
<meta property="og:site_name" content="napari.org" />
```

### PR DESCRIPTION
**Pull request by codemonkey800**
## Description

Closes #277 

This adds the necessary metadata tags for napari.org so that we can display rich previews on OpenGraph websites and Twitter. This works by using the following data for the preview data:

- Title: `H1` heading on the page.
- Description: Content defined in `intro` or `metaDescription` theme variables.
- Image: URL defined in `previewImage` theme variable, or use the first `img` tag on the page.

### Pages without images

- [Demo](https://napari-org-rich-preview.vercel.app/release/index.html)
- [OpenGraph Test](https://www.opengraph.xyz/url/https%3A%2F%2Fnapari-org-rich-preview.vercel.app%2Frelease%2Findex.html/)

image

### Pages with images using first image

- [Demo](https://napari-org-rich-preview.vercel.app/tutorials/index.html)
- [OpenGraph Test](https://www.opengraph.xyz/url/https%3A%2F%2Fnapari-org-rich-preview.vercel.app%2Ftutorials%2Findex.html/)

image

image

### Pages with images using `previewImage` variable

```md
---
theme:
  intro: The napari.org guides page.
  previewImage: /spongebob.jpg
---

# Guides

...
```

- [Demo](https://napari-org-rich-preview.vercel.app/guides/stable/index.html)
- [OpenGraph Test](https://www.opengraph.xyz/url/https%3A%2F%2Fnapari-org-rich-preview.vercel.app%2Fguides%2Fstable%2Findex.html/)

image

### CODE REVIEW

**Comment by neuromusic** [comment]
there are a couple of things that seem to be off re: functionality...

- the title is reflecting the "title" of the page, not the first H1 tag (specifically... it looks like we're appending ` - napari` and it should be dropped for the cards)
- the pages without images don't seem to be rendering right on Twitter...

image

they also don't seem to be passing Twitter's card validator: https://cards-dev.twitter.com/validator

it looks like I made a mistake in the spec & we're missing something in the metadata tags

**Comment by neuromusic** [comment]
wait, that's weird...

its working for Releases, but not Plugins...

image


image

**Comment by neuromusic** [comment]
does this have something to do w/ the hybrid build process? the "stable" in the plugins URL tells me that its coming from `napari/napari`

**Comment by kne42** [comment]
i find it kind of odd that pages without images preview with nothing. shouldn't we have a banner or something with the napari logo at least?

**Comment by codemonkey800** [comment]
> does this have something to do w/ the hybrid build process? the "stable" in the plugins URL tells me that its coming from `napari/napari`

@neuromusic Right now I am conditionally rendering the meta tags if certain pages do not have the required metadata:

> PR Description
> > The title and description are required, so if one is undefined, the page will not render the meta tags.

Right now, the demo adds descriptions for the [release](https://napari-org-rich-preview.vercel.app/release/index.html), [guides](https://napari-org-rich-preview.vercel.app/guides/stable/index.html), and [tutorials](https://napari-org-rich-preview.vercel.app/tutorials/index.html) pages, but it is not included in the PR.

I think every page has an `H1` tag already, so if we want to enable previews for every page, we need to either:

1. Provide `metaDescription` or `intro` to every page
1. Automatically find a description to render in the preview. Maybe the first `H2` or paragraph tag?

**Comment by codemonkey800** [comment]
> i find it kind of odd that pages without images preview with nothing. shouldn't we have a banner or something with the napari logo at least?

I didn't implement this with a design dependency in mind, but we can include a banner! Did you have something in mind? Would also like to hear from @liaprins-czi

**Comment by codemonkey800** [comment]
@neuromusic Actually I wonder if we can render previews without descriptions. If it works, then we can include a preview for every page, but some pages won't have a description unless one is provided explicitly

**Comment by codemonkey800** [comment]
@neuromusic give it a try now, it should work for every page. if the page doesn't have a description or intro, then it'll look like:

image

**Comment by liaprins-czi** [comment]
> > i find it kind of odd that pages without images preview with nothing. shouldn't we have a banner or something with the napari logo at least?
> 
> I didn't implement this with a design dependency in mind, but we can include a banner! Did you have something in mind? Would also like to hear from @liaprins-czi

Just to make sure I am understanding this issue/ask, is the problem that it is possible to post to a social media channel (e.g. Twitter) without includeing an image, but it'd be better to alway have an image, even just a generic one that would work for any post? Or is the issue something else.... @kne42 what do you mean by "images preview with nothing"?

**Comment by codemonkey800** [comment]
> it is possible to post to a social media channel (e.g. Twitter) without includeing an image, but it'd be better to alway have an image

@liaprins-czi it's this one, if there's no image on the page, it'll show something like this:
image

So ideally most websites will provide a default image for us, but it would be nice to have napari-specific banner or something

**Comment by neuromusic** [comment]
Twitter actually recommends against using a generic image:

from https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary

> A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages.

**Comment by neuromusic** [comment]
I'm not strongly opposed though. If we do use a "default" image, let's use the one w/ cells on Tutorials rather than the astronaut (see #102): https://napari.org/tutorials/index.html

**Comment by neuromusic** [comment]
>Automatically find a description to render in the preview. Maybe the first H2 or paragraph tag?

I like grabbing the first N characters of the first paragraph is there is no description

**Comment by liaprins-czi** [comment]
> If we do use a "default" image, let's use the one w/ cells on Tutorials rather than the astronaut (see #102): https://napari.org/tutorials/index.html

Yeah,that sounds good to me! Will this solve the issue, or do we need any other sort of image made?

**Comment by codemonkey800** [comment]
> > Automatically find a description to render in the preview. Maybe the first H2 or paragraph tag?
> 
> I like grabbing the first N characters of the first paragraph is there is no description

What is the value of N? 😅

**Comment by codemonkey800** [comment]
Actually I think the recommended limit is 200 so we can use that

**Comment by neuromusic** [comment]
200 works for me :D

**Comment by codemonkey800** [comment]
@neuromusic @liaprins-czi The cells image is now used as the default image and the description is sourced from the first paragraph in the page:

image

However, if there are no paragraph elements in the page, then it'll be blank unless an intro or description is provided in the markdown frontmatter

**Comment by neuromusic** [comment]
🤩

**Review by neuromusic — APPROVED** [review]
implementation look great!!!

**Review by sofroniewn — APPROVED** [review]
Looks awesome!

**Comment by neuromusic** [comment]
example on image.sc...

image

**Pull request merged**
