### PR TITLE
Replace embedded Google Calendar

### LINKED ISSUE #271: replace embedded Google Calendar to address shortcomings
The embedded Google Calendar suffers from...

- an outdated UI
- which is inconsistent with our current designs
- and is not responsive etc

image

We should find a way to render the iCal in a way that is more user friendly & aligned with the site's design.

For reference...
- public link: https://calendar.google.com/calendar/embed?src=c_35r93ec6vtp8smhm7dv5uot0v4%40group.calendar.google.com
- calendar id: c_35r93ec6vtp8smhm7dv5uot0v4@group.calendar.google.com

### PR DESCRIPTION
**Pull request by codemonkey800**
## Description

This replaces the Google Calendar iframe with a custom built Calendar component using [react-calendar](https://github.com/wojtekmaj/react-calendar) and the [Calendar JavaScript API](https://developers.google.com/calendar/api/quickstart/js).

I opted to use `react-calendar` over [react-google-calendar](https://github.com/ericz1803/react-google-calendar) because the latter lacked certain APIs required for the level of functionality we wanted. With that in mind, it might be a good idea to find a way to contribute back to the repo or maybe create a library of our own.

## Demos

https://napari-org-calendar.vercel.app/community/meeting_schedule.html

### CODE REVIEW

**Comment by codemonkey800** [comment]
@isabela-pf For days that have a lot of events, Google Calendar will show a small text button with a popup:

https://user-images.githubusercontent.com/2176050/145503500-deb09bf8-72de-4bbb-a1d3-994f77fbaa03.mp4

For this PR's implementation, I made it scrollable, but I'm curious if you have a better idea for how to handle this 🤔 

https://user-images.githubusercontent.com/2176050/145503334-4c98ca83-42c0-4555-bcac-4aba70e93ccd.mp4

**Review by liaprins-czi — COMMENTED** [review]
This looks so good! And you built it so quickly, nice work! There's just a couple of things I noticed that could be good if could update them:
- In the narrower screenview, filter dropdown with the checkboxes is not aligned with the calendar
Screen Shot 2021-12-10 at 2 11 01 PM
- when I clicked to add the napari calendar to my Google calendar, it was calling it "Napari Meetings" with a capital "N" ... to be consistent with name of napari, can we change that to "napari Meetings" with a lowercase "n"? (I don't know if this is something you would be able to change, though)
Screen Shot 2021-12-10 at 2 07 55 PM


Great work!

**Review by isabela-pf — COMMENTED** [review]
This is looking really good! So good I actually had to play around with it for a while before I could figure out what I wanted to comment on. Thanks for putting so much work into the details. I’m starry-eyed 🤩

Responding to your question about days with more events than the box allows, I have a few thoughts
- Your scroll choice makes sense. I think there’s the risk of it not being clear that there are events users can’t see until they scroll.
- My initial plan was to have the height of a day’s box get longer until all events are visible. I don’t know that it’s actually a good idea, though, since I don’t know of any kind of limit on how many events could be in a single day.
- I noticed that Google calendars use the `+n more` button approach, but I didn’t like that you have to go through multiple overlays to get to an event’s details.

I haven’t been able to come up with another idea today, and don’t think it’s important enough to block this PR when there is a solution in place. I can give this some more thought and let this stick with the scroll for now.

Some other comments:
- I noticed it looks like some of the weeks on the month view are different sizes. Is it that the current week gets taller until all events are visible without scrolling? Or are my eyes playing tricks on me? I like the idea, though what would happen if there were to be, for example, 20 events somehow someday?
- I like the choice to use the squares for only the current week in the monthly and weekly view!
- I’m happy to find that I can tab through the calendar pretty well! :tada: I think this is an edge case, but using only a keyboard I can’t find a way to close the event details overlay, so it’s possible to open several of them at once. I wanted to tell you in case it’s a wacky symptom of a larger problem.

https://user-images.githubusercontent.com/50221806/145652755-0ad96efd-51e4-42da-a21e-d4e22f5b9804.mov

In the community meeting yesterday, people also asked if the calendar could be on its own page to solve the easy to find, easy to link, and more helpful link preview requests from the original issue. It was also said this could be a separate PR; just making note for record-keeping purposes.

**Comment by codemonkey800** [comment]
> when I clicked to add the napari calendar to my Google calendar, it was calling it "Napari Meetings" with a capital "N" ... to be consistent with name of napari, can we change that to "napari Meetings" with a lowercase "n"? (I don't know if this is something you would be able to change, though)

@liaprins-czi that's something we'll need to change from Google Calendar cc: @sofroniewn

**Comment by codemonkey800** [comment]
> I noticed it looks like some of the weeks on the month view are different sizes. Is it that the current week gets taller until all events are visible without scrolling? Or are my eyes playing tricks on me? I like the idea, though what would happen if there were to be, for example, 20 events somehow someday?

I think the designs show the active week with taller days, or is that only for the first week? 

image

> using only a keyboard I can’t find a way to close the event details overlay, so it’s possible to open several of them at once. I wanted to tell you in case it’s a wacky symptom of a larger problem.

This is fixed now! Opening the popup will now trap focus on the tooltip so that it prevents scrolling and tabbing outside of the tooltip. You can also press `Escape` to close the tooltip 😄

**Comment by codemonkey800** [comment]
Also @isabela-pf I've created a separate page for the calendar. Let me know if we need to update anything 😄 

https://napari-org-calendar.vercel.app/calendar.html

**Review by liaprins-czi — APPROVED** [review]
LGTM! 😃

**Comment by isabela-pf** [comment]
Thank you for all these fixes @codemonkey800!

> I think the designs show the active week with taller days, or is that only for the first week?

That’s on me for not being clear. When I made it, I was thinking that the height of the week expanded until it showed all the meetings on the longest day. 

I checked in with @liaprins-czi about this since I wasn't happy with any of my ideas so far. We agreed that it might be best for this first implementation of the month view to have each week's height determined by the day with the most events. So each week could potentially be a different height, but it ensures no events are accidentally hidden (which is the main concern we both shared).

> This is fixed now! Opening the popup will now trap focus on the tooltip so that it prevents scrolling and tabbing outside of the tooltip. You can also press Escape to close the tooltip 😄

Perfect! This is also great because it now makes the links within the tooltip navigable by keyboard. I looked into trapping focus just to check that there weren’t accessibility issues to be aware of from that, but it seems okay based on this [WAI-ARIA modal example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html) (I'm linking more for my reference so I don’t forgetfully ask someone this question again later on 😆 )

As for the separate page question, I think it solves the problem of links having a relevant preview and having a single link, but I think I might like it to preserve the navigation from the main napari.org by being a napari.org page. Something like

napari.org with a new Meeting Schedule page holding only the community calendar and related information.

Does anyone else have thoughts on this? (P.S. thanks for marking changes so clearly and making it easy to respond to!)

**Comment by sofroniewn** [comment]
@nclack can you address https://github.com/napari/napari.github.io/pull/302#issuecomment-992993685 (capitalization comment) I think you have permissions there.

> As for the separate page question, I think it solves the problem of links having a relevant preview and having a single link, but I think I might like it to preserve the navigation from the main napari.org by being a napari.org page. Something like

That looks great!

**Comment by nclack** [comment]
> capitalization

@sofroniewn  done

**Comment by codemonkey800** [comment]
> I checked in with @liaprins-czi about this since I wasn't happy with any of my ideas so far. We agreed that it might be best for this first implementation of the month view to have each week's height determined by the day with the most events. So each week could potentially be a different height, but it ensures no events are accidentally hidden (which is the main concern we both shared).

@isabela-pf sounds good, the calendar has been updated to match what you described!

> napari.org with a new Meeting Schedule page holding only the community calendar and related information.
> 
> Does anyone else have thoughts on this? (P.S. thanks for marking changes so clearly and making it easy to respond to!)

That sounds good to me! I already went ahead and pushed a commit with these changes (which you can view here https://napari-org-calendar.vercel.app/community/meeting_schedule.html), however I'm curious if @sofroniewn or @melissawm had any thoughts on this too 🤔

**Review by sofroniewn — APPROVED** [review]
This all looks great to me! I'm approving. I'm not sure why there are test fails, but we can merge this when ready. will be great to have it in!!

**Review by isabela-pf — APPROVED** [review]
Hooray! This looks lovely!

**Comment by melissawm** [comment]
Note that some of the changes made in this PR were overwritten by https://github.com/napari/napari.github.io/commit/600b484ba8dc5abee3a1d410f3ffa161f18551ff (because the actual source for these documents live at napari/napari)

**Comment by codemonkey800** [comment]
> Note that some of the changes made in this PR were overwritten by [600b484](https://github.com/napari/napari.github.io/commit/600b484ba8dc5abee3a1d410f3ffa161f18551ff) (because the actual source for these documents live at napari/napari)

I noticed 😢 I updated the TOC manually so that the changes are included, but I can't wait for the docs build process to be improved 😆

**Comment by neuromusic** [comment]
what do we need to do to get these changes live? do we need an issue and PR onto napari/napari?

**Comment by sofroniewn** [comment]
> what do we need to do to get these changes live? do we need an issue and PR onto napari/napari?

I'm not sure, @codemonkey800?

**Comment by codemonkey800** [comment]
@neuromusic @sofroniewn I think it should work if we update it there since it seems the overwrites are coming from napari/napari 🤔 Let me create a PR with the changes

**Comment by codemonkey800** [comment]
@sofroniewn Opened a PR, please review when you get a chance 😄 
https://github.com/napari/napari/pull/3912

**Pull request merged**
