### PR TITLE
Fix calendar link in 0.4.18 version docs

### PR DESCRIPTION
**Pull request by melissawm**
Addresses #374

Hopefully this is enough to fix it, let me know if you think something else is needed @psobolewskiPhD !

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
We can give this a whirl, but 0.4.16 calendar has that change (@) and also doesn't work:
image

Meanwhile, 0.4.17 which does work the html seems identical to 0.4.18 which doesn't 🤯

**Comment by melissawm** [comment]
Argh. Ok, I'll take a look later - probably won't be before tomorrow though. Sorry!

**Comment by melissawm** [comment]
Ok - I think this may have been missed because I built the docs locally to post on the 0.4.18 release version but I don't have the permission to generate the calendar, which involves using an env variable at build time: https://napari.org/napari-sphinx-theme/demo/kitchen-sink/calendar.html

I will need help from someone with the right token for this.

**Comment by melissawm** [comment]
Superseded by #389

**Pull request closed without merging**
