### PR TITLE
Update point annotator application for magicgui 0.2

### PR DESCRIPTION
**Pull request by kevinyamauchi**
As @allenleetc helpfully pointed out in https://github.com/kevinyamauchi/PointAnnotator/issues/2, our point annotation example is currently broken by the `magicgui` 0.2 API change. This PR updates the application note to be compatible with  napari > 0.4.3 and magicgui > 0.2.5 (I will test with the newest versions soon)..

### CODE REVIEW

**Comment by GenevieveBuckley** [comment]
It might be worth adding a note somewhere in the text saying that users should have magicgui > 0.2.5

I know @jni was interested in having versioned docs of the tutorials, not sure if he has any thoughts on whether we also need to keep track of the magicgui versions in this way too.

**Comment by kevinyamauchi** [comment]
> It might be worth adding a note somewhere in the text saying that users should have magicgui > 0.2.5

Great point, @GenevieveBuckley . I will add that note.

**Comment by kevinyamauchi** [comment]
I have finished updating the tutorial and added the note about magicgui compatibility. I think this is ready for review!

**Review by sofroniewn — APPROVED** [review]
Looks great to me! thanks @kevinyamauchi for the updates!!

**Pull request merged**
